# -----------------------------------------------------------------
# Файл для тестирования API
#
# Порядок выполнения:
# 1. Запрос 'register' (если нужно создать пользователя)
# 2. Запрос 'login'
# 3. Запрос 'getTasks' (теперь он должен работать)
# -----------------------------------------------------------------

###
# @name register
# Регистрация нового пользователя
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "user-for-test@example.com",
    "password": "password123"
}

###
# @name login
# Вход в систему. Ответ этого запроса будет использован ниже.
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "test1"
}

###
# @name getTasks
# Получение списка задач.
# Этот запрос зависит от успешного выполнения запроса 'login'.
# Он берет 'accessToken' из ответа 'login'.
#
# ВАЖНО: Между '###' и 'GET' должна быть пустая строка, чтобы
# объявление переменной не "прилипло" к запросу 'login'.

@accessToken = {{login.response.body.access_token}}

GET http://localhost:8080/tasks
Authorization: Bearer {{accessToken}}

###
# @name createTask
POST http://localhost:8080/tasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title":"test task 1"
}

###
# @name logout
POST http://localhost:8080/auth/logout
Authorization: Bearer {{accessToken}}